### ISSUE TITLE
502 Proxy Error 

### ISSUE THREAD

**Issue by teuzindahuz** [EMODnet/Web-Service-Documentation#3]
While trying the [tutorial](https://github.com/EMODnet/Web-Service-Documentation/blob/06dcebfdcc413fb4e053b9855cfa13dcfb0f1fee/R-tutorial/EMODnet_web_services_in_R_part2.ipynb), I cannot open to the url provided in the In [10] due to a [502 Proxy Error](https://www.emodnet.eu/geonetwork/emodnet/eng/csw?REQUEST=GetRecords&SERVICE=CSW&VERSION=2.0.2&ELEMENTSETNAME=summary&OUTPUTSCHEMA=http://www.opengis.net/cat/csw/2.0.2&CONSTRAINTLANGUAGE=FILTER&CONSTRAINT_LANGUAGE_VERSION=1.1.0&RESULTTYPE=results&TYPENAMES=csw:Record&CONSTRAINT=%3Cogc:Filter%20xmlns:ogc=%22http://www.opengis.net/ogc%22%3E%3Cogc:PropertyIsEqualTo%3E%3Cogc:PropertyName%3Edc:type%3C/ogc:PropertyName%3E%3Cogc:Literal%3Edataset%3C/ogc:Literal%3E%3C/ogc:PropertyIsEqualTo%3E%3C/ogc:Filter%3E&maxRecords=1000)

**Comment by bart-v** [comment]
We have increased the timeout, and the page will now load (after a 1-2 mins)

It's better to work in a paginated way.
Plus, there is no real need to filter on type "dataset"

A request like this will only take a few seconds to load:
```
/geonetwork/emodnet/eng/csw?REQUEST=GetRecords&SERVICE=CSW&VERSION=2.0.2&ELEMENTSETNAME=summary&OUTPUTSCHEMA=http://www.opengis.net/cat/csw/2.0.2&CONSTRAINTLANGUAGE=FILTER&CONSTRAINT_LANGUAGE_VERSION=1.1.0&RESULTTYPE=results&TYPENAMES=csw:Record
```
