### ISSUE TITLE
List R package EMODnetWFS

### ISSUE THREAD

**Issue by salvafern** [EMODnet/Web-Service-Documentation#5]
Hi @tim-collart !

The EMODnetWFS R package is becoming more and more robust. @maelle @annakrystalli and I think it is a good moment to add it to the different web services documentation of EMODnet (See https://github.com/EMODnet/EMODnetWFS/issues/73)

Are you ok with adding a small section about the package to this page? 

If you agree we can write it and make a pull request.

**Comment by tim-collart** [comment]
Hi @salvafern ,
Yes, that sounds great. Indeed just sending a pull request will be the easiest. If you want it to work with the Binder instance, we may need to add some of the dependencies in:
- any additional R packages go in https://github.com/EMODnet/Web-Service-Documentation/blob/main/install.R
- any other system dependencies go in https://github.com/EMODnet/Web-Service-Documentation/blob/main/apt.txt
- This is the current R version it is running, we can consider updating it if required: https://github.com/EMODnet/Web-Service-Documentation/blob/main/runtime.txt

Best wishes, 
Tim
