### ISSUE TITLE
Available WCS versions

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/Web-Service-Documentation#8]
Hi @tim-collart !

Is there a way to detect (or is it documented somewhere) what versions of WCS can be used with the EMODnet endpoints? 

For example I've been trying to get info from the biology service and seem to get ok responses with `2.0.1` but errors with `2.1.0`. 

Any suggestions on how I might be able to detect versions that will work would be greatly appreciated!

Let me know if you want a detailed example.

**Comment by tim-collart** [comment]
Dear @annakrystalli,

You can read it from the ows:ServiceTypeVersion in the GetCapabilities. e.g. for Biology
https://geo.vliz.be/geoserver/Emodnetbio/wcs?SERVICE=WCS&REQUEST=GetCapabilities

```
<ows:ServiceTypeVersion>2.0.1</ows:ServiceTypeVersion>
<ows:ServiceTypeVersion>1.1.1</ows:ServiceTypeVersion>
<ows:ServiceTypeVersion>1.1.0</ows:ServiceTypeVersion>
```

Best wishes,
Tim

**Comment by annakrystalli** [comment]
Great! Many thanks @tim-collart !
